---
- name: CTFd playbook
  hosts: aws_ec2
  become: yes
  become_method: sudo
  tasks:
    - name: CTFd Setup
      include_role:
        name: setup

    - name: CTFd Config
      include_role:
        name: config
